/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#131b2e",
        "surface-container-highest": "#e0e3e5",
        "error-container": "#ffdad6",
        "primary": "#006948",
        "on-secondary-container": "#684000",
        "on-primary-fixed-variant": "#005137",
        "tertiary": "#545c72",
        "on-secondary-fixed": "#2a1700",
        "secondary-fixed-dim": "#ffb95f",
        "surface-container": "#eceef0",
        "surface-container-lowest": "#ffffff",
        "error": "#ba1a1a",
        "surface-variant": "#e0e3e5",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#dae2fd",
        "on-surface-variant": "#3d4a42",
        "on-primary-container": "#f5fff7",
        "on-error-container": "#93000a",
        "surface": "#f7f9fb",
        "surface-bright": "#f7f9fb",
        "on-tertiary-fixed-variant": "#3f465c",
        "primary-container": "#00855d",
        "inverse-primary": "#68dba9",
        "on-primary-fixed": "#002114",
        "outline-variant": "#bccac0",
        "secondary-fixed": "#ffddb8",
        "tertiary-container": "#6c748b",
        "on-background": "#191c1e",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "outline": "#6d7a72",
        "inverse-on-surface": "#eff1f3",
        "surface-container-high": "#e6e8ea",
        "surface-tint": "#006c4a",
        "background": "#f7f9fb",
        "on-tertiary-container": "#fefcff",
        "secondary": "#855300",
        "inverse-surface": "#2d3133",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "surface-dim": "#d8dadc",
        "primary-fixed": "#85f8c4",
        "secondary-container": "#fea619",
        "on-surface": "#191c1e",
        "on-secondary-fixed-variant": "#653e00",
        "primary-fixed-dim": "#68dba9",
        "tertiary-fixed-dim": "#bec6e0"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "container-max": "1280px",
        "2xl": "48px",
        "base": "4px",
        "lg": "24px",
        "3xl": "64px",
        "sidebar-width": "280px",
        "xl": "32px",
        "sm": "12px",
        "xs": "8px",
        "md": "16px",
        "gutter": "24px"
      },
      fontFamily: {
        "code-md": ["JetBrains Mono"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "label-md": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "display-lg": ["Inter"],
        "display-sm": ["Inter"],
        "headline-lg": ["Inter"],
        "body-sm": ["Inter"],
        "title-lg": ["Inter"],
        "headline-md": ["Inter"]
      },
      fontSize: {
        "code-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "60px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-sm": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["30px", { lineHeight: "38px", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "title-lg": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }]
      },
      maxWidth: {
        "container-max": "1280px"
      }
    }
  },
  plugins: [],
}
